version: '3'
services:
  db:
    image: postgres:12.0-alpine
    restart: always
    environment:
      POSTGRES_DB: ontop_wallet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      backend:
        ipv4_address: 172.16.238.10
    ports:
      - "5435:5432"
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.16.238.11
volumes:
  db-data:

networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
